apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-ipxe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-ipxe
subjects:
- kind: ServiceAccount
  name: build-ipxe
